- alias: Fingerling42
  fullName: Ivan Berman
  avatar: 'IBerman.svg'

- alias:  Leemo
  fullName: Leemo
  avatar: 'Leemo.png'

- alias: Vourhey
  fullName: Vadim Manaenko
  avatar: 'VManaenko.jpeg'

- alias: Ensrationis
  fullName: Sergei Lonshakov
  avatar: 'SLonshakov.jpeg'

- alias: wimmer_savinova
  fullName: Anna Wimmer-Savinova
  avatar: 'AWimmer-Savinova.jpg'

- alias: PaTara43
  fullName: Pavel Tarasov
  avatar: 'PTarasov.jpeg'